version: "3"
services:
  # db:
  #   image: mongo
  #   volumes:
  #     - ./data:/data/db
  #   networks:
  #     - db_net
  web:
    image: jamianv/axonradio:v1
    command: python -u main.py
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - db_net

networks:
  db_net:
